### FTP Host ##
FTPH='103.249.100.221'
FTPU='pns111'
FTPPWD='hanhung'
INC='https://raw.githubusercontent.com/thanhdiepts/tdcr-xmlbk-2.2/master/etc/inc/cloudcfg.inc'
CHECKIP='https://raw.githubusercontent.com/thanhdiepts/tdcr-xmlbk-2.2/master/root/checkip.sh'
CLOUDBK='https://raw.githubusercontent.com/thanhdiepts/tdcr-xmlbk-2.2/master/root/cloudbk.sh'
IFXML='https://raw.githubusercontent.com/thanhdiepts/tdcr-xmlbk-2.2/master/root/_if_xml.php'
INITCLOUDBK='https://raw.githubusercontent.com/thanhdiepts/tdcr-xmlbk-2.2/master/root/initcloudbk.sh'
